[book]
title = "Linux Systems Administration"
authors = ["C. Sean Burns"]
description = "Entry level book on Linux systems administration."
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/cseanburns/linux_sysadmin"
site-url = "https://cseanburns.net/"

[output.html.print]
enable = true
page-break = true

[output.html.search]
enable = true            # enables the search feature
limit-results = 30       # maximum number of search results
teaser-word-count = 30   # number of words used for a search result teaser
use-boolean-and = true   # multiple search terms must all match
boost-title = 2          # ranking boost factor for matches in headers
boost-hierarchy = 1      # ranking boost factor for matches in page names
boost-paragraph = 1      # ranking boost factor for matches in text
expand = true            # partial words will match longer terms
heading-split-level = 3  # link results to heading levels
copy-js = true           # include Javascript code for search
